### ISSUE TITLE
Bug: Pagination show-last variant clickable on overflow icon

### ISSUE THREAD

**Issue by abiyasa** [eBay/ebayui-core-react#174]
On pagination variant show-last, when I click the overflow icon, the pagination suddenly expanded and stops working properly (not triggering on Select). To reproduce:

- Open storybook https://opensource.ebay.com/ebayui-core-react/main/index.html?path=/story/ebay-pagination--variant-showlast-interactive (ebay-ui-core-react v3.6.0)
- Click the overflow  (...) icon
- The pagination suddenly expanded and you cannot update the selected page anymore

See video below

https://user-images.githubusercontent.com/1072047/205666370-499cc953-d703-41a6-9a0a-baac7316a914.mov

Expected:

- The overflow icon should not be clickable for show-last. The icon should be not interactive (see eBay skin https://opensource.ebay.com/skin/#pagination)

**Comment by darkwebdev** [comment]
looks like it was broken by `overflow` implementation
