### ISSUE TITLE
Skin 16.0.0 changes 

### ISSUE THREAD

**Issue by montoya332** [eBay/ebayui-core-react#217]
16.0.0 Roadmap: 
https://github.com/orgs/eBay/projects/8/views/2

Callouts : 

- Icon changes including program badges : 
  - icons
    - https://github.com/eBay/skin/pull/2016
    - https://github.com/eBay/ebayui-core/issues/1869
  - bages:
    - https://github.com/eBay/skin/pull/2013
    - https://github.com/eBay/ebayui-core/issues/1871

**Comment by darkwebdev** [comment]
released in v4.0.0
