### ISSUE TITLE
Chevron icon is too large after Skin 16.1.0 update

### ISSUE THREAD

**Issue by joinfelipe** [eBay/ebayui-core-react#229]
latest skin version removed some CSS override which made the chevron look smaller. As a result the icon size has changed.

<img width="620" alt="Screenshot 2023-05-12 at 12 58 45 PM" src="https://github.com/eBay/ebayui-core-react/assets/69696226/a65fc603-9d7c-4e15-bf10-1fa095f8cfb1">

**Comment by darkwebdev** [comment]
deployed
