### ISSUE TITLE
Prevent default preselection in Listbox component

### ISSUE THREAD

**Issue by renka** [eBay/ebayui-core-react#247]
The requirement is that, on page load, the dropdown should display only a placeholder without any preselected value. Once the user selects an option, they should not be able to deselect it. 
The similar behavior is in Marko:
https://opensource.ebay.com/ebayui-core/?path=/story/buttons-ebay-listbox-button--standard

**Comment by renka** [comment]
https://github.com/eBay/ebayui-core-react/pull/248

**Comment by darkwebdev** [comment]
wow, looks like it's a bug:
https://opensource.ebay.com/ebayui-core-react/main/?path=/story/ebay-listbox-button--default-no-selected-option

thanks for reporting!
