### ISSUE TITLE
Incorrect Icon Displayed in `EbayProgressStepper` for Active Step

### ISSUE THREAD

**Issue by lbn21** [eBay/ebayui-core-react#253]
I have been utilising the `EbayProgressStepper` component and noticed that the icon representing the current active step doesn't seem to be the expected one. I am unsure if there were recent changes to this component that may have led to this inconsistency.

Upon further inspection, I found that the `active` state is utilising `stepperConfirmation24` instead of what I anticipated to be `stepperCurrent24`. Here is a snippet of the code:

```js
const typeIcons: { [key in StepState]: Icon } = {
    complete: 'stepperConfirmation24',
    attention: 'stepperAttention24',
    upcoming: 'stepperUpcoming24',
    active: 'stepperConfirmation24'
}
```

Would someone be able to confirm if this is the intended behaviour or if there's a recent update that altered this mapping? Thank you!

**Comment by darkwebdev** [comment]
Hey man! Progress stepper doesn't use current step icon anymore. It was changed in Skin: https://opensource.ebay.com/skin/#progress-stepper
Also Marko version behaves the same way: https://opensource.ebay.com/ebayui-core/?path=/story/progress-ebay-progress-stepper--in-progress
