### ISSUE TITLE
README: Document about pass-through attributes feature

### ISSUE THREAD

**Issue by pcanella** [eBay/ebayui-core-react#26]
Original issue: https://github.corp.ebay.com/React/ebayui-core-react/issues/387

Just like the eBayUI Core Marko principles, eBayUI Core React also supports all valid HTML attributes on all its components (e.g `id`, `aria-*`, `data-*`, `tabindex`, `style`, ...) by using **pass through** feature.

The Marko has documented this feature on its readme (see https://github.com/eBay/ebayui-core#pass-through-attributes) but not on our React part.

Adding this feature to our document will help to solve questions/problems like [this on Slack](https://ebay-eng.slack.com/archives/C103YQUQG/p1650927826291499) especially for new users, who are not familiar with eBayUI Core Marko and not aware that most eBayUI Core component supports any HTML attributes.

**Comment by darkwebdev** [comment]
Thank you @abiyasa for the orginal issue.
