### ISSUE TITLE
Detect missing variables on hook dependency array

### ISSUE THREAD

**Issue by pcanella** [eBay/ebayui-core-react#27]
Original issue: https://github.corp.ebay.com/React/ebayui-core-react/issues/374

This is a follow-up from issue #347 , where we got stale props due to not properly stating variables on hook dependency array. This problem is hard to detect and also not easy to test. 

One options is to **introduce [eslint rule eslint-plugin-react-hooks](https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks)** to help us detecting this kind of problems.

**Comment by abiyasa** [comment]
Closing this one as it's duplicated by https://github.com/eBay/ebayui-core-react/issues/37
