### ISSUE TITLE
Snackbar `animated` prop does nothing

### ISSUE THREAD

**Issue by ericbiewener** [eBay/ebayui-core-react#383]
The docs & types indicated that the snackbar dialog takes an `animated: boolean` prop, but [the component does not actually use this](https://github.com/eBay/ebayui-core-react/blob/main/src/ebay-snackbar-dialog/components/ebay-snackbar-dialog.tsx). As a result, it is always animated.

**Comment by HenriqueLimas** [comment]
The `animated` property is used by dialog base [here](https://github.com/eBay/ebayui-core-react/blob/main/src/ebay-dialog-base/dialog-base-with-state.tsx#L16). It is enabled by default, by passing it to false, the animation is removed from the snackbar
