### ISSUE TITLE
page scrolls up to the top when the user clicks on listbox-button

### ISSUE THREAD

**Issue by montoya332** [eBay/ebayui-core-react#4]
Old default 
setTimeout(() => optionsContainerRef.current.focus(), 0)
https://user-images.githubusercontent.com/8145951/176749394-85dbf522-9fa4-4a99-9f2e-5c7ec0b90654.mov
May want add preventScroll Param
New 
setTimeout(() => optionsContainerRef.current.focus({ preventScroll: true }), 0)
https://user-images.githubusercontent.com/8145951/176749418-cf2c426d-12c1-4597-88c5-af8682ed1749.mov

**Comment by darkwebdev** [comment]
fixed by #6
