### ISSUE TITLE
Upgrade storybook with addons

### ISSUE THREAD

**Issue by pcanella** [eBay/ebayui-core-react#40]
Original issue: https://github.corp.ebay.com/React/ebayui-core-react/issues/268

- @storybook/react should be 6+
- @storybook/addon-storyshots should be 6+

documentation: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-configure

Both `render` and `config` properties will be deprecated in v6 and removed in v7:
```js
initStoryshots({
    renderer: mount,
    config: ({ configure }) =>
        configure(() => {
            require('./index.stories')
        }, module)
})
```

possible changes in `jest.config.js`:

```js
{
transform: {
        '^.+\\.[jt]sx?$': 'ts-jest'
    },
globals: {
        'ts-jest': {
            tsConfig: {
                allowJs: true
            }
}
```

**Comment by abiyasa** [comment]
Closing this issue since we have upgraded to Storybook v6 before went open source
