### ISSUE TITLE
Replace static id on EbayListboxButton in case of prefixId is defined

### ISSUE THREAD

**Issue by pcanella** [eBay/ebayui-core-react#43]
## Problems

As a follow up from PR #252, which used static id on the button span when the EbayListboxButton has `prefixId` (see [this comment](https://github.corp.ebay.com/React/ebayui-core-react/pull/252#discussion_r1802388)). The use of static id will cause another accessibility issue if we have more than 1 EbayListboxButton on the same page (more than 1 element with the same id).

Marko widget/component [has the concept of 'key'](https://markojs.com/docs/class-components/#key) where it can automatically generate unique id for an HTML element. React does not have this out-of-the-box (see issue #210).

## Solutions

Please replace static id with dynamic id. However, please take in mind that we can't use random id here since it will cause problem when you re-hydrate a server-side-rendered page on browser. 

## Related Issues

The solution is related to issue #210

**Comment by abiyasa** [comment]
Not an issue anymore since id is not static anymore but generated using prefixId.

https://github.com/eBay/ebayui-core-react/blob/3b3903fe913a4ac60dcca8f6d124cd48e70c73b6/src/ebay-listbox-button/listbox-button.tsx#L203-L226
