### ISSUE TITLE
EbayWindowNotice

### ISSUE THREAD

**Issue by pcanella** [eBay/ebayui-core-react#46]
Would be nice to have:
https://ebay.github.io/skin/archive/v9.5/ds6/index.html#notice

<img width="801" alt="1e13c000-96d6-11ea-87a7-95aa51b6c982" src="https://user-images.githubusercontent.com/4923719/179612433-49e0cf5f-1e74-4b30-b4d5-09fa6249ff5b.png">
<img width="334" alt="22d87400-96d6-11ea-8882-62483b334eff" src="https://user-images.githubusercontent.com/4923719/179612456-f00b3b8f-9411-4a74-8527-931889a55759.png">

**Comment by darkwebdev** [comment]
window notice is deprecated
