### ISSUE TITLE
Extend test for EbayDialog

### ISSUE THREAD

**Issue by pcanella** [eBay/ebayui-core-react#47]
As a follow up for bugfix on aria-hidden: https://github.corp.ebay.com/React/ebayui-core-react/pull/120#issuecomment-1329665

The test should test if the aria-hidden is set accordingly in case of dialog is open and closed. Possible test case:

- mount dialog with other divs
```
mount(
  <>
    <div id="test-1"/>
    <div id="test-2"/>
    <EbayDialog>...</EbayDialog>
    <div id="test-3"/>
  </>
)
```
- Assert no aria-hidden on test divs
- trigger dialog to show
- Assert aria-hidden=true on test divs
- trigger dialog to close
- Assert no aria-hidden on test divs

**Comment by abiyasa** [comment]
Not an issue anymore since @HenriqueLimas  has replaced our custom ariaHidder with makeup js
