### ISSUE TITLE
Replace `addon-info` with `addon-docs`

### ISSUE THREAD

**Issue by pcanella** [eBay/ebayui-core-react#50]
addon-info is deprecated in storybook v6

![e3335100-0c8b-11ea-92ad-b1f17cfd4e59](https://user-images.githubusercontent.com/4923719/179612817-7e35927f-7fed-43d8-80cd-b16e7364faa8.png)

https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
https://github.com/storybookjs/storybook/blob/next/addons/docs

**Comment by abiyasa** [comment]
Closing this since we have done it when upgrading to storybook v6
