### ISSUE TITLE
ebay-menu-button

### ISSUE THREAD

**Issue by pcanella** [eBay/ebayui-core-react#51]
https://github.com/eBay/ebayui-core/tree/master/src/components/ebay-menu-button

Original `eBayUI` API compatibility:
- [x] DOM structure of the component is preserved
- [ ] All original attributes are supported
- [x] All original events are triggered

Documentation & tests:
- [x] Readme
- [x] Rendering tests (snapshots/manual)
- [x] Interaction tests (clicking, etc)
- [x] Storybook has examples with multiple use-cases

**Comment by darkwebdev** [comment]
will be released in v4.x
