### ISSUE TITLE
Clean-up release and git tags

### ISSUE THREAD

**Issue by abiyasa** [eBay/ebayui-core-react#62]
When renaming the repo to ui-core-react (see PR #57 ), we reset the version back to version 1.0.0

There are currently [80+ release tags from the old releases](https://github.com/eBay/ebayui-core-react/tags), when we're still using the old name. These old tags potentially can break our release in the future. The new version might clash with the existing older version so version bumping will failed since the git tag has already existed. 

While this version clash will happen somewhen in the future when we reach version 9.13 but it's best if we clean up git tags earlier.

## Actions

We can delete the following tags or rename them to `ebayui-core-react@vXX.X.X`:

- Tags from [9.13.1](https://github.com/eBay/ebayui-core-react/releases/tag/9.13.1) to [10.0.17](https://github.com/eBay/ebayui-core-react/releases/tag/10.0.17)
- Tags with prefix 'v', from [v10.0.12](https://github.com/eBay/ebayui-core-react/releases/tag/v10.0.12) to [v10.0.10](https://github.com/eBay/ebayui-core-react/releases/tag/v10.0.10)

**Comment by HenriqueLimas** [comment]
@abiyasa I think we should rename them instead of delete them. We could add a prefix `ebayui-core-react@vXX.X.X`

**Comment by abiyasa** [comment]
That's a good idea 👍 Let me update the issue

**Comment by darkwebdev** [comment]
done
