### ISSUE TITLE
ebay-page-notice: Update icon size based on Skin v14.12.0

### ISSUE THREAD

**Issue by abiyasa** [eBay/ebayui-core-react#77]
Skin v14.12.0 contains changes on Page Notice which make the icon smaller and some adjusted spacing.

Since the page notice icon is rendered by our ebay-icon, we need to change our implementation to use the right icon sizes: https://github.com/eBay/ebayui-core-react/blob/e13c4e6f9beba01ce19ba8c2c94d77c3dec57357/src/ebay-page-notice/page-notice.tsx#L31-L37

Before:

![Before Skin v14.12.0](https://user-images.githubusercontent.com/1675667/184721132-dd1e218c-3275-43db-af58-a280a6ec0075.png)

After:

![After Skin v14.12.0](https://user-images.githubusercontent.com/1675667/184721771-c598f9d2-a7ba-47d9-ad03-20214ef7ec4b.png)

See related issues:

- Skin v14.12.0 release: https://github.com/eBay/skin/releases/tag/v14.2.0
- PR on Skin, updating page notice: https://github.com/eBay/skin/pull/1838

**Comment by HenriqueLimas** [comment]
Available on v1.5.0
